services:
  - type: web
    name: wexa-ai-startup-ecosystem-api
    runtime: node
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: COGNODB_URI
        sync: false
      - key: COGNODB_PASSWORD
        sync: false
      - key: COGNODB_USER
        value: cognodb
